site:
  template: standard
  updated: true
  navBar:
    links:
      - title: Courses
        link: /courses
      - title: Events
        link: /events
      - title: Blog
        link: /blogs
  brand:
    logo: /img/brand/logo.png
    darkLogo: /img/brand/logo-dark.png
    description: Master the art of product building and turn your ideas into
      successful, scalable products
    ogImage: /icon/torqbit.png
    themeSwitch: true
    defaultTheme: light
    favicon: /favicon.ico
    socialLinks:
      discord: https://discord.gg/NserMXcx
      github: https://github.com/torqbit
      youtube: https://youtube.com/@torqbit
    name: Torqbit
    brandColor: "#8980fd"
    title: Modern education starts here
    icon: https://cdn.torqbit.com/static/brand-icon.png
  darkMode: true
  heroSection:
    title: Welcome to Torqbit Academy
    description: >
      Torqbit, is an open source learning platform to help businesses simplify the onboarding and training of their customers
    actionButtons:
      primary:
        label: Get Started
        link: /dashboard
      secondary:
        label: Contact Us
        link: mailto:support@torqbit.com
    banner:
      lightModePath: /img/landing/hero-bg.png
      darkModePath: /img/landing/hero-bg-dark.png
      position: background
  sections:
    features:
      enabled: true
      title: Our Features
      description: Our educational platform is completely secure, robust and scales to
        millions of users, and always available, giving you the flexibility to
        learn from anywhere, anytime.
      items:
        - img: /img/landing/auth.png
          title: Social Login
          description: Login with any of the support networking platform like Google,
            Github or Facebook
          link: /docs/auth
        - img: /img/landing/laptop.png
          title: Portable
          description: Access the course lessons and assignments from anywhere and from
            any device.
          link: /docs/auth
        - img: /img/landing/event.png
          title: Events
          description: Connect with the educator through offline or online events and
            workshops.
    courses:
      enable: true
      title: Our Courses
      description: Learn from the best instructors around the world
    learning:
      enabled: true
      title: Our Learning path
      description: "Learn from the best instructors around the world "
      enable: false
    blog:
      enable: true
      title: Blogs
      description: Description on blogs
    faq:
      enabled: true
      items: null
      title: FAQ
      description: Frequently asked questions by the students
    testimonials:
      enabled: true
      title: "Teachers love our product "
      description: "Find out what excites our users, when using our product "
      items: null
