site:
  template: standard
  updated: true
  navBar:
    links:
      - title: Courses
        link: /#courses
      - title: Events
        link: /events
      - title: Blog
        link: /blog
  brand:
    logo: /img/brand/logo.png
    darkLogo: /img/brand/logo-dark.png
    description: Master the art of product building and turn your ideas into
      successful, scalable products
    ogImage: /icon/torqbit.png
    favicon: /favicon.ico
    socialLinks:
      discord: https://discord.gg/NserMXcx
      github: https://github.com/torqbit
      youtube: https://www.youtube.com/@torqbit
    name: Torqbit
    brandColor: "#747df0"
    title: Making online education delightful and easy
    icon: /icon/torqbit.png
  darkMode: true
  heroSection:
    title: Making online education delightful and easy
    description: >
      Torqbit, an open-source platform, serves as a learning management software
      that works for single person to largest educational institutions
    actionButtons:
      primary:
        label: Get Started
        link: /dashboad
      secondary:
        label: Contact Us
        link: mailto:support@torqbit.com
    banner:
      lightModePath: /img/landing/hero-bg.png
      darkModePath: /img/landing/hero-bg-dark.png
      position: background
  sections:
    features:
      title: Get Started
      description: Features for the learning platform
      items:
        - img: /img/landing/auth.png
          title: hjjjh
          description: jjgk
          link: /docs/auth
        - img: /static/1733490998141-feature-secondicon.png
          title: Authentication
          description: Configure authentication with Google, Github or any other auth provider supported by NextAuth
          link: /docs/auth
        - img: /static/1733494176234-feature-thirdicon.jpg
          title: Email
          description: Configure authentication

    courses:
      enable: false
      title: Courses list
      description: Courses description for alll
    blog:
      enable: true
      title: Blogs
      description: Description on blogs
