apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdEAxMjM=
  MYSQL_DATABASE: dG9ycWJpdGRiCg==
  MYSQL_USER: dG9ycWJpdA==
  MYSQL_PASSWORD: dG9ycWJpdDEyMw==