apiVersion: v1
kind: Secret
metadata:
  name: torqbit-secrets
type: Opaque
data:
  DATABASE_URL: bXlzcWw6Ly90b3JxYml0OnRvcnFiaXQxMjNAbXlzcWwtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvdG9ycWJpdGRi
  NEXT_PUBLIC_SECRET: MVJJcHliZVJIazIxeG10emsyampQeHZheUFEOEZFdEhhdVFUYng4YlNoRT0=
  JWT_SECRET: cDFSRGVSNTJDcGdIa1pRSkdGY0ZGYzlHcjFrVlRuSWpFQnhhYnFrcStBbz0=
  NEXTAUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
  ADMIN_EMAIL: dGVzdEBtYWlsLmNvbQ==
  NEXT_PUBLIC_APP_ENV: ZGV2ZWxvcG1lbnQ=
  NODE_ENV: cHJvZHVjdGlvbg==
  GATEWAY_PROVIDER_NAME: Q0FTSEZSRUU=
  NEXT_SMTP_HOST: c210cC5yZXNlbmQuY29t
  NEXT_SMTP_USER: cmVzZW5k
  NEXT_PUBLIC_NEXTAUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
