-- AlterTable
ALTER TABLE `Notification` MODIFY `objectType` ENUM('USER', 'COURSE', 'LEARNING_PATH', 'EVENT', 'VIDEO_LESSON', 'ASSIGNMENT_LESSON', 'VIDEO', 'ASSIGNMENT') NOT NULL,
    MODIFY `subjectType` ENUM('USER', 'COURSE', 'LEARNING_PATH', 'EVENT', 'VIDEO_LESSON', 'ASSIGNMENT_LESSON', 'VIDEO', 'ASSIGNMENT') NOT NULL;
