-- AlterTable
ALTER TABLE `ServiceProvider` ADD COLUMN `state` ENUM('INITIATED', 'AUTHENTICATED', 'VOD_CONFIGURED', 'CDN_CONFIGURED', 'STORAGE_CONFIGURED', 'CMS_CONFIGURED', 'PAYMENT_CONFIGURED', 'EMAIL_CONFIGURED') NOT NULL DEFAULT 'INITIATED';
