export type IEmailEventType =
  | "TEST_EMAIL_CREDENIDTIALS"
  | "NEW_USER"
  | "VERIFY_EMAIL"
  | "TRIAL_SUBSCRIPTION_EXPIRE_REMINDER"
  | "TENANT_SUBSCRIPTION"
  | "SUBSCRIPTION_EXPIRE_REMINDER"
  | "NEW_TENANT";
