services:
  web:
    image: torqbit/toq:v1.0.4
    ports:
      - "8080:8080"
    command: ["sh", "-c", "npx prisma db push --accept-data-loss; PORT=8080 yarn start"]

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/auth/session || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    environment:
      # Core
      NODE_ENV: "production"
      PORT: 8080

      # Database
      DATABASE_OS_URL: "mysql://admin:torq123@db:3306/torqbitdb"

      # Auth + URLs
      NEXTAUTH_SECRET: "dev-secret-change-me"
      NEXTAUTH_URL: "http://localhost:8080"
      NEXT_PUBLIC_NEXTAUTH_URL: "http://localhost:8080"
      NEXT_PUBLIC_APP_ENV: "development"

      # Vector DB (Qdrant)
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      # Cookies / domains
      COOKIE_DOMAIN: "localhost"

      # Email
      NEXT_SMTP_HOST: "smtp.resend.com"
      NEXT_SMTP_USER: "resend"
      NEXT_SMTP_EMAIL: "no-reply@resend.com"
      NEXT_SMTP_PASSWORD: "password"

      # App settings
      ADMIN_EMAIL: "admin@example.com"
      CRAWLEE_STORAGE_DIR: "/tmp/crawlee"
      EMBED_SCRIPT_PATH: "https://cdn.torqbit.com/static/js/chat-embed.dev.js"

      # Puppeteer cache (if used)
      PUPPETEER_CACHE_DIR: "/root/.puppeteer-cache"

    networks:
      - app-network

  db:
    image: mysql:8.2.0
    hostname: db.torqbit.com
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    ports:
      - "3360:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: torq123
      MYSQL_DATABASE: torqbitdb
    volumes:
      - db-data:/var/lib/mysql

    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:v1.15.3
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  qdrant-data:
